kind: pipeline
type: docker
name: site-deploy

steps:
  - name: build
    image: hugo:latest
    pull: never
    commands:
      - hugo --minify

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: 172.17.0.1
      port: 32179
      username: root
      key:
        from_secret: SSH_KEY
      source: public/*
      target: /var/www/site

trigger:
  branch:
    - main
