kind: pipeline
type: docker
name: site-deploy

steps:
  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: 172.17.0.1
      port: 32179
      username: root
      key:
        from_secret: SSH_KEY
      source:
        - index.html
      target: /var/www/site

trigger:
  branch:
    - main
